replicaCount: 2

namespace: webbfolio

image:
  repository: ghcr.io/lawebb-org/webbfolio
  tag: ""
  pullPolicy: IfNotPresent
  pullSecrets: [] # e.g. ["ghcr-cred"]

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: false
  className: ""
  hosts:
    - host: webbfolio.local
      paths:
        - path: /
          pathType: Prefix
  tls: [] # - secretName: webbfolio-tls; hosts: ["webbfolio.example.com"]

resources: {}
#  limits:
#    cpu: 250m
#    memory: 256Mi
#  requests:
#    cpu: 50m
#    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70

podAnnotations: {}
podLabels: {}

env: []
# - name: NEXT_PUBLIC_ANALYTICS_ID
#   value: "xyz"

envFromSecret: "" # name of secret with runtime env (optional)
envFromConfig: "" # name of configmap with runtime env (optional)

nodeSelector: {}
tolerations: []
affinity: {}

securityContext:
  fsGroup: 1001

containerSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  periodSeconds: 5
startupProbe:
  httpGet:
    path: /
    port: http
  failureThreshold: 30
  periodSeconds: 5
