name: Build, Publish and Deploy
on:
    push:
        tags:
            - "v*.*.*"

jobs:
    build-and-push-webbfolio-image:
        uses: lawebb-org/webbfolio/.github/workflows/build-and-push-image.yaml@main
        with:
            image_name: ghcr.io/lawebb-org/webbfolio
            image_tag: latest
            description: A personal website and portfolio for lawebb built with NextJs
            dockerfile: ./infra/docker/webbfolio/Dockerfile
            package: webbfolio
            context: .
        secrets:
            registry_username: ${{ vars.CR_USERNAME }}
            registry_token: ${{ secrets.CR_TOKEN }}

    create-and-upload-helm-package-directory:
        runs-on: ubuntu-latest
        steps:
            - name: Create Helm Package Directory
              run: |
                  rm -rf .helm-packages
                  mkdir -p .helm-packages

            - name: Upload Helm Package Directory
              uses: actions/upload-artifact@v4
              with:
                  name: helm-package-directory
                  path: .helm-packages

    package-webbfolio-chart:
        needs: [create-and-upload-helm-package-directory]
        uses: lawebb-org/webbfolio/.github/workflows/package-chart.yaml@main
        with:
            chart_name: ./infra/charts/webbfolio
            shared_folder: helm-package-directory

    release-charts:
        needs: [package-webbfolio-chart]
        runs-on: ubuntu-latest
        steps:
            - name: Release Charts
              uses: helm/chart-releaser-action@v1.6.0
              with:
                  skip_packaging: true
              env:
                  CR_TOKEN: "${{ secrets.CR_TOKEN }}"

    deploy:
        needs: [release-charts, build-and-push-webbfolio-image]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
