name: Build, Publish and Deploy
on:
    push:
        tags:
            - "v*.*.*"

jobs:
    build-and-push-webbfolio-image:
        uses: lawebb-org/webbfolio/.github/workflows/build-and-push-image.yaml@main
        with:
            image_name: ghcr.io/lawebb-org/webbfolio
            image_tag: latest
            description: A personal website and portfolio for lawebb built with NextJs
            dockerfile: ./infra/docker/webbfolio/Dockerfile
            package: webbfolio
            context: .
        secrets:
            registry_username: ${{ vars.CR_USERNAME }}
            registry_token: ${{ secrets.CR_TOKEN }}

    package-webbfolio-chart:
        uses: lawebb-org/webbfolio/.github/workflows/package-chart.yaml@main
        with:
            chart_name: ./infra/charts/webbfolio

    release-charts:
        needs: [package-webbfolio-chart]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Download Helm Package Directory
              uses: actions/download-artifact@v4
              with:
                  pattern: "*-helm-package-directory"
                  path: .helm-packages
                  merge-multiple: true

            - name: Release Charts
              uses: helm/chart-releaser-action@v1.7.0
              with:
                  skip_packaging: true
              env:
                  CR_TOKEN: "${{ secrets.CR_TOKEN }}"

    deploy:
        needs: [release-charts, build-and-push-webbfolio-image]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
