name: Package Chart
on:
    workflow_call:
        inputs:
            chart_name:
                required: true
                type: string

jobs:
    package-webbfolio-chart:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Helm
              uses: azure/setup-helm@v1
              with:
                  version: v3.19.0

            - name: Package Webbfolio Helm Chart
              run: |
                  mkdir -p .helm-packages
                  VERSION=${{github.ref_name}}
                  helm package ${{inputs.chart_name}} --app-version=${VERSION:1} --version=${VERSION:1} --destination=.helm-packages

            - name: Upload Helm Package Directory
              uses: actions/upload-artifact@v4
              with:
                  name: webbfolio-helm-package-directory
                  path: .helm-packages
                  if-no-files-found: error
                  include-hidden-files: true
